services:
  - docker

before_install:
  - docker build -t heberyl/react-test -f ./client/Dockerfile.dev .

script:
  - docker run heberyl/react-test npm test -- --coverage

after_success:
  - docker build -t heberyl/react-client ./client
  - docker build -t heberyl/react-nginx ./nginx
  - docker build -t heberyl/react-server ./server
  - docker build -t heberyl/react-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push heberyl/react-client
  - docker push heberyl/react-nginx
  - docker push heberyl/react-server
  - docker push heberyl/react-worker
